services:
  - type: web
    name: discord-nuke-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    autoDeploy: true
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: GUILD_ID
        sync: false
